package com.thuoghtworks.android.challenge.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BATTLE".
 */
public class Battle {

    private Long id;
    private String region;
    private String attacker_outcome;
    private String location;
    private String attacker_commander;
    private String defender_size;
    private Integer major_capture;
    private String name;
    private Integer year;
    private String note;
    private String defender_king;
    private String attacker_size;
    private String attacker_king;
    private String attacker_1;
    private String defender_1;
    private Integer major_death;
    private String defender_3;
    private String defender_2;
    private String defender_4;
    private String battle_type;
    private String summer;
    private Integer battle_number;
    private String defender_commander;
    private String attacker_2;
    private String attacker_3;
    private String attacker_4;
    private Integer attacker_king_id;
    private Integer defender_king_id;
    private Integer winner_king_id;
    public Battle() {
    }

    public Battle(Long id) {
        this.id = id;
    }

    public Battle(Long id, String region, String attacker_outcome, String location, String attacker_commander, String defender_size, Integer major_capture, String name, Integer year, String note, String defender_king, String attacker_size, String attacker_king, String attacker_1, String defender_1, Integer major_death, String defender_3, String defender_2, String defender_4, String battle_type, String summer, Integer battle_number, String defender_commander, String attacker_2, String attacker_3, String attacker_4, Integer attacker_king_id, Integer defender_king_id, Integer winner_king_id) {
        this.id = id;
        this.region = region;
        this.attacker_outcome = attacker_outcome;
        this.location = location;
        this.attacker_commander = attacker_commander;
        this.defender_size = defender_size;
        this.major_capture = major_capture;
        this.name = name;
        this.year = year;
        this.note = note;
        this.defender_king = defender_king;
        this.attacker_size = attacker_size;
        this.attacker_king = attacker_king;
        this.attacker_1 = attacker_1;
        this.defender_1 = defender_1;
        this.major_death = major_death;
        this.defender_3 = defender_3;
        this.defender_2 = defender_2;
        this.defender_4 = defender_4;
        this.battle_type = battle_type;
        this.summer = summer;
        this.battle_number = battle_number;
        this.defender_commander = defender_commander;
        this.attacker_2 = attacker_2;
        this.attacker_3 = attacker_3;
        this.attacker_4 = attacker_4;
        this.attacker_king_id = attacker_king_id;
        this.defender_king_id = defender_king_id;
        this.winner_king_id = winner_king_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getRegion() {
        return region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    public String getAttacker_outcome() {
        return attacker_outcome;
    }

    public void setAttacker_outcome(String attacker_outcome) {
        this.attacker_outcome = attacker_outcome;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getAttacker_commander() {
        return attacker_commander;
    }

    public void setAttacker_commander(String attacker_commander) {
        this.attacker_commander = attacker_commander;
    }

    public String getDefender_size() {
        return defender_size;
    }

    public void setDefender_size(String defender_size) {
        this.defender_size = defender_size;
    }

    public Integer getMajor_capture() {
        return major_capture;
    }

    public void setMajor_capture(Integer major_capture) {
        this.major_capture = major_capture;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getYear() {
        return year;
    }

    public void setYear(Integer year) {
        this.year = year;
    }

    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public String getDefender_king() {
        return defender_king;
    }

    public void setDefender_king(String defender_king) {
        this.defender_king = defender_king;
    }

    public String getAttacker_size() {
        return attacker_size;
    }

    public void setAttacker_size(String attacker_size) {
        this.attacker_size = attacker_size;
    }

    public String getAttacker_king() {
        return attacker_king;
    }

    public void setAttacker_king(String attacker_king) {
        this.attacker_king = attacker_king;
    }

    public String getAttacker_1() {
        return attacker_1;
    }

    public void setAttacker_1(String attacker_1) {
        this.attacker_1 = attacker_1;
    }

    public String getDefender_1() {
        return defender_1;
    }

    public void setDefender_1(String defender_1) {
        this.defender_1 = defender_1;
    }

    public Integer getMajor_death() {
        return major_death;
    }

    public void setMajor_death(Integer major_death) {
        this.major_death = major_death;
    }

    public String getDefender_3() {
        return defender_3;
    }

    public void setDefender_3(String defender_3) {
        this.defender_3 = defender_3;
    }

    public String getDefender_2() {
        return defender_2;
    }

    public void setDefender_2(String defender_2) {
        this.defender_2 = defender_2;
    }

    public String getDefender_4() {
        return defender_4;
    }

    public void setDefender_4(String defender_4) {
        this.defender_4 = defender_4;
    }

    public String getBattle_type() {
        return battle_type;
    }

    public void setBattle_type(String battle_type) {
        this.battle_type = battle_type;
    }

    public String getSummer() {
        return summer;
    }

    public void setSummer(String summer) {
        this.summer = summer;
    }

    public Integer getBattle_number() {
        return battle_number;
    }

    public void setBattle_number(Integer battle_number) {
        this.battle_number = battle_number;
    }

    public String getDefender_commander() {
        return defender_commander;
    }

    public void setDefender_commander(String defender_commander) {
        this.defender_commander = defender_commander;
    }

    public String getAttacker_2() {
        return attacker_2;
    }

    public void setAttacker_2(String attacker_2) {
        this.attacker_2 = attacker_2;
    }

    public String getAttacker_3() {
        return attacker_3;
    }

    public void setAttacker_3(String attacker_3) {
        this.attacker_3 = attacker_3;
    }

    public String getAttacker_4() {
        return attacker_4;
    }

    public void setAttacker_4(String attacker_4) {
        this.attacker_4 = attacker_4;
    }

    public Integer getAttacker_king_id() {
        return attacker_king_id;
    }

    public void setAttacker_king_id(Integer attacker_king_id) {
        this.attacker_king_id = attacker_king_id;
    }

    public Integer getDefender_king_id() {
        return defender_king_id;
    }

    public void setDefender_king_id(Integer defender_king_id) {
        this.defender_king_id = defender_king_id;
    }

    public Integer getWinner_king_id() {
        return winner_king_id;
    }

    public void setWinner_king_id(Integer winner_king_id) {
        this.winner_king_id = winner_king_id;
    }

    @Override
    public String toString() {
        return "Battle{" +
                "id=" + id +
                ", region='" + region + '\'' +
                ", attacker_outcome='" + attacker_outcome + '\'' +
                ", location='" + location + '\'' +
                ", attacker_commander='" + attacker_commander + '\'' +
                ", defender_size='" + defender_size + '\'' +
                ", major_capture=" + major_capture +
                ", name='" + name + '\'' +
                ", year=" + year +
                ", note='" + note + '\'' +
                ", defender_king='" + defender_king + '\'' +
                ", attacker_size='" + attacker_size + '\'' +
                ", attacker_king='" + attacker_king + '\'' +
                ", attacker_1='" + attacker_1 + '\'' +
                ", defender_1='" + defender_1 + '\'' +
                ", major_death=" + major_death +
                ", defender_3='" + defender_3 + '\'' +
                ", defender_2='" + defender_2 + '\'' +
                ", defender_4='" + defender_4 + '\'' +
                ", battle_type='" + battle_type + '\'' +
                ", summer='" + summer + '\'' +
                ", battle_number=" + battle_number +
                ", defender_commander='" + defender_commander + '\'' +
                ", attacker_2='" + attacker_2 + '\'' +
                ", attacker_3='" + attacker_3 + '\'' +
                ", attacker_4='" + attacker_4 + '\'' +
                ", attacker_king_id=" + attacker_king_id +
                ", defender_king_id=" + defender_king_id +
                ", winner_king_id=" + winner_king_id +
                '}';
    }
}
