package com.thuoghtworks.android.challenge.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Entity mapped to table "KING".
 */
public class King implements Parcelable {

    private Long id;
    private String name;
    private Float rating;
    private Integer total_won_count;
    private Integer total_loss_count;
    private Integer attack_won_count;
    private Integer defend_won_count;
    private Integer btype_pitched_count;
    private Integer btype_ambush_count;
    private Integer btype_seige_count;
    private Integer btype_razing_count;

    public King() {
    }

    public King(Long id) {
        this.id = id;
    }

    public King(Long id, String name, Float rating, Integer total_won_count, Integer total_loss_count, Integer attack_won_count, Integer defend_won_count, Integer btype_pitched_count, Integer btype_ambush_count, Integer btype_seige_count, Integer btype_razing_count) {
        this.id = id;
        this.name = name;
        this.rating = rating;
        this.total_won_count = total_won_count;
        this.total_loss_count = total_loss_count;
        this.attack_won_count = attack_won_count;
        this.defend_won_count = defend_won_count;
        this.btype_pitched_count = btype_pitched_count;
        this.btype_ambush_count = btype_ambush_count;
        this.btype_seige_count = btype_seige_count;
        this.btype_razing_count = btype_razing_count;
    }

    public King(String name) {
        this.name = name;
        this.rating = Float.parseFloat("0");
        this.total_won_count = 0;
        this.total_loss_count = 0;
        this.attack_won_count = 0;
        this.defend_won_count = 0;
        this.btype_pitched_count = 0;
        this.btype_ambush_count = 0;
        this.btype_seige_count = 0;
        this.btype_razing_count = 0;
    }
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Float getRating() {
        return rating;
    }

    public void setRating(Float rating) {
        this.rating = rating;
    }

    public Integer getTotal_won_count() {
        return total_won_count;
    }

    public void setTotal_won_count(Integer total_won_count) {
        this.total_won_count = total_won_count;
    }

    public Integer getTotal_loss_count() {
        return total_loss_count;
    }

    public void setTotal_loss_count(Integer total_loss_count) {
        this.total_loss_count = total_loss_count;
    }

    public Integer getAttack_won_count() {
        return attack_won_count;
    }

    public void setAttack_won_count(Integer attack_won_count) {
        this.attack_won_count = attack_won_count;
    }

    public Integer getDefend_won_count() {
        return defend_won_count;
    }

    public void setDefend_won_count(Integer defend_won_count) {
        this.defend_won_count = defend_won_count;
    }

    public Integer getBtype_pitched_count() {
        return btype_pitched_count;
    }

    public void setBtype_pitched_count(Integer btype_pitched_count) {
        this.btype_pitched_count = btype_pitched_count;
    }

    public Integer getBtype_ambush_count() {
        return btype_ambush_count;
    }

    public void setBtype_ambush_count(Integer btype_ambush_count) {
        this.btype_ambush_count = btype_ambush_count;
    }

    public Integer getBtype_seige_count() {
        return btype_seige_count;
    }

    public void setBtype_seige_count(Integer btype_seige_count) {
        this.btype_seige_count = btype_seige_count;
    }

    public Integer getBtype_razing_count() {
        return btype_razing_count;
    }

    public void setBtype_razing_count(Integer btype_razing_count) {
        this.btype_razing_count = btype_razing_count;
    }

    @Override
    public String toString() {
        return "King{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", rating=" + rating +
                ", total_won_count=" + total_won_count +
                ", total_loss_count=" + total_loss_count +
                ", attack_won_count=" + attack_won_count +
                ", defend_won_count=" + defend_won_count +
                ", btype_pitched_count=" + btype_pitched_count +
                ", btype_ambush_count=" + btype_ambush_count +
                ", btype_seige_count=" + btype_seige_count +
                ", btype_razing_count=" + btype_razing_count +
                '}';
    }


    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeString(this.name);
        dest.writeValue(this.rating);
        dest.writeValue(this.total_won_count);
        dest.writeValue(this.total_loss_count);
        dest.writeValue(this.attack_won_count);
        dest.writeValue(this.defend_won_count);
        dest.writeValue(this.btype_pitched_count);
        dest.writeValue(this.btype_ambush_count);
        dest.writeValue(this.btype_seige_count);
        dest.writeValue(this.btype_razing_count);
    }

    protected King(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.name = in.readString();
        this.rating = (Float) in.readValue(Float.class.getClassLoader());
        this.total_won_count = (Integer) in.readValue(Integer.class.getClassLoader());
        this.total_loss_count = (Integer) in.readValue(Integer.class.getClassLoader());
        this.attack_won_count = (Integer) in.readValue(Integer.class.getClassLoader());
        this.defend_won_count = (Integer) in.readValue(Integer.class.getClassLoader());
        this.btype_pitched_count = (Integer) in.readValue(Integer.class.getClassLoader());
        this.btype_ambush_count = (Integer) in.readValue(Integer.class.getClassLoader());
        this.btype_seige_count = (Integer) in.readValue(Integer.class.getClassLoader());
        this.btype_razing_count = (Integer) in.readValue(Integer.class.getClassLoader());
    }

    public static final Parcelable.Creator<King> CREATOR = new Parcelable.Creator<King>() {
        @Override
        public King createFromParcel(Parcel source) {
            return new King(source);
        }

        @Override
        public King[] newArray(int size) {
            return new King[size];
        }
    };
}
